# docker-compose.yml
services:
  k6:
    build:
      context: .
      dockerfile: Dockerfile.k6
    environment:
      - K6_OUT=influxdb=http://influxdb:${INFLUXDB_PORT}/k6
      - TARGET_HOST=${TARGET_HOST}
      - TARGET_PORT=${TARGET_PORT}
      - HOST_HEADER=${HOST_HEADER}
      - VUS_INITIAL=${VUS_INITIAL}
      - VUS_MAX=${VUS_MAX}
      - RAMP_UP_DURATION=${RAMP_UP_DURATION}
      - STEADY_STATE_DURATION=${STEADY_STATE_DURATION}
      - RAMP_DOWN_DURATION=${RAMP_DOWN_DURATION}
    networks:
      - loadtest-network
      - app_network
    volumes:
      - ./load-tests:/scripts
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8
    networks:
      - loadtest-network
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    networks:
      - loadtest-network
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

networks:
  loadtest-network:
    driver: bridge
  app_network:
    external: true
    name: ${EXTERNAL_NETWORK}

volumes:
  influxdb-data:
  grafana-data:
